### ISSUE TITLE
Include link to ULID generator demo API in README

### ISSUE THREAD

**Issue by grempe** [ryan-mars/ulid-workers#3]
Perhaps you'd like to include a link to this online ULID generator that runs as a Cloudflare Worker and makes use of the code from this repo. I think it provides a good demo of the library as it is also easily configurable in quantity, monotonicity, and seed value.

## README

https://github.com/truestamp/ulid-generator/blob/main/README.md

# API

https://ulid.truestamp.com/?q=10

**Comment by ryan-mars** [comment]
Since it's your project, how about a PR? I'll be happy to merge.
